Update testing instruction
project-codeflare/codeflare-sdk pull request #140
Opened 2023-05-31 22:38 UTC by tedhtchang

Improve testing instruction for contributors to run the unit tests.

2023-05-31 23:02 UTC, anishasthana submitted a review, later dismissed

2023-05-31 23:02 UTC, anishasthana commented on README.md
> +> Some tests, i.e. test_ray_details,test_cluster_status,and test_wait_ready require an Openshift cluster with [Codeflare Stack](https://github.com/opendatahub-io/distributed-workloads/blob/main/Quick
```suggestion
> Some tests, i.e. test_ray_details, test_cluster_status, and test_wait_ready require an OpenShift cluster with the [Codeflare Stack](https://github.com/opendatahub-io/distributed-workloads/blob/main/Quick-Start.md#quick-start-guide-for-distributed-workflows-with-the-codeflare-stack) installed.
```

2023-06-07 19:16 UTC, anishasthana reviewed
/lgtm

2023-06-07 21:01 UTC, MichaelClifford requested changes

2023-06-07 21:01 UTC, MichaelClifford commented on README.md
> +> Some tests, i.e. test_ray_details, test_cluster_status, and test_wait_ready require an OpenShift cluster with the [Codeflare Stack](https://github.com/opendatahub-io/distributed-workloads/blob/main
I don't think this is true. Unless something has changed recently, all of the unit tests can be run locally **without** an OpenShift Cluster. 

We use mocker to fake any required OC responses.

2023-06-07 22:11 UTC, tedhtchang commented
Thanks @MichaelClifford. I verified again they don't need a real cluster.

2023-06-12 13:55 UTC, MichaelClifford approved these changes

2023-06-12 13:57 UTC, MichaelClifford commented
LGTM @tedhtchang thanks for the changes :)

2023-06-12 15:04 UTC, merged