Remove oc client and add helper functions
project-codeflare/codeflare-sdk pull request #187
Opened 2023-06-28 20:31 UTC by tedhtchang

closes #173

2023-07-04 09:44 UTC, Bobbins228 commented
LGTM Just tested it out working as expected nice work Ted

2023-07-04 09:45 UTC, Bobbins228 approved these changes
LGTM Just tested it out working as expected nice work Ted

2023-07-09 19:49 UTC, Maxusmusti requested changes
Lookg good, just needs a rebase and a couple of very small nits

2023-07-09 19:49 UTC, Maxusmusti commented on src/codeflare_sdk/cluster/cluster.py
>  from kubernetes import client, config
Double import?

2023-07-09 19:49 UTC, Maxusmusti commented on tests/unit_test.py
> +        side_effect=d,
what is `d` here?

2023-07-10 21:48 UTC, carsonmh commented
Tested it out and it works as expected. LGTM!

2023-07-10 23:17 UTC, carsonmh approved these changes

2023-07-13 17:29 UTC, merged