CLI Layout and Create RayCluster function
project-codeflare/codeflare-sdk pull request #227
Opened 2023-07-14 21:39 UTC by carsonmh

Creates layout, configuration, build configuration, and create raycluster command for the CLI. After building, get stated with `codeflare --help` or just `codeflare`

### How to test
- Running unit tests `pytest -v tests/unit_test.py` or `python -m pytest tests/unit_test.py`
- After building SDK, you can run `codeflare create raycluster [options]` command. This should create the yaml file with the specified options.

2023-07-21 14:34 UTC, MichaelClifford commented on tests/unit_test.py
> +    create_cluster_command = """
should this be renames to `define_cluster_command`?

2023-07-21 14:41 UTC, MichaelClifford requested changes
Really minor change otherwise looks good. Tested the CLI and define function as well. All seems to work as expected

:+1:

2023-07-21 16:19 UTC, Maxusmusti requested changes
Off to a good start! Just one thing I noticed initially:
 - Running `codeflare create raycluster` for me causes `FileNotFoundError: [Errno 2] No such file or directory: '/Users/meyceoz/Documents/codeflare-sdk/src/codeflare_sdk/cli/commands/create.py'`. I realized after that the command was changed to `define` but the CLI should be able to handle erroneous input. For example, if i write `codeflare pizza`, right now it will tell me `FileNotFoundError: [Errno 2] No such file or directory: '/Users/meyceoz/Documents/codeflare-sdk/src/codeflare_sdk/cli/commands/pizza.py'`. Basically, just make sure you are checking that commands are valid too, not just options, and if not just tell the user it is invalid and to check `--help` for more details. I think `click` may have something for this as well.

2023-07-25 18:45 UTC, MichaelClifford commented
@carsonmh looks good. Thanks for the changes. 

However, your commit history looks like you merged previous commits instead of re-baseing. Can you update this PR so that it only includes your commits? 

Thanks

2023-07-25 19:15 UTC, Maxusmusti commented
@MichaelClifford it should be fixed now

2023-07-25 19:30 UTC, Maxusmusti requested changes
LGTM, only one unit-test suggestion, then good to merge

2023-07-25 19:52 UTC, Maxusmusti approved these changes
LGTM

2023-07-25 19:52 UTC, Maxusmusti commented
@MichaelClifford if it looks good to you, feel free to merge

2023-07-25 20:51 UTC, MichaelClifford approved these changes

2023-07-26 15:38 UTC, merged