CLI Authentication
project-codeflare/codeflare-sdk pull request #252
Opened 2023-07-26 19:16 UTC by carsonmh

# Issue link
closes #217

# What changes have been made
Made login and logout functions in the CLI, allowing the user to authenticate into their Kubernetes cluster using token + server. Also added `load_auth` function which loads the authentication configuration so the SDK can use it.

# Verification steps
- `codeflare login` and `codeflare logout` are the two functions to be tested. Can be run in the terminal after building SDK with `pip install -e .`
- Unit tests can be run in usual way with `pytest -v tests/unit_test.py` or `python -m pytest tests/unit_test.py`

## Checks
- [x] I've made sure the tests are passing. 
- Testing Strategy
   - [x] Unit tests
   - [x] Manual tests
   - [ ] Testing is not required for this change

2023-07-27 18:40 UTC, Maxusmusti commented
This would be a good one for @Bobbins228 to review as well, as he's pretty familiar with the new auth updates

2023-07-28 12:44 UTC, Bobbins228 approved these changes
LGTM! Can confirm login and logout work as they should and tests pass nice work Carson

2023-07-28 19:13 UTC, Maxusmusti requested changes
Put this in slack, but adding this here as well so nobody accidentally merges without seeing:

Looks good, just a couple of things:
 - When things are saved in "auth", that's an actual file getting created and stored, right? If so, be careful about using a relative path, as people may login, move to a different dir, then be confused as to why they are logged out. We may instead want this file to be in a set `~/.codeflare/auth`
 - In your unit tests, it may be worth checking that the contents of the `auth` file are as you expect as well
 - Just checking, where is the `load_auth()` function going to be used, is it going to be at the start of every other CLI function?
 - I'm assuming this is just for token auth? That makes sense, as users can otherwise just do their own `export KUBECONFIG=...` if they need to change default kubeconfig path. I would just test and make sure that that option still works as expected

2023-07-31 15:14 UTC, Maxusmusti approved these changes
LGTM

2023-07-31 15:20 UTC, merged