Changed min/max workers to single field
project-codeflare/codeflare-sdk pull request #266
Opened 2023-08-01 21:41 UTC by Maxusmusti

# Issue link
#232 

# What changes have been made
Replaced `min_worker` and `max_worker` with a single consistent worker field in cluster config

# Verification steps
Create a cluster
check `cluster.details()`
check the actual cluster details

## Checks
- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] Testing is not required for this change

2023-08-01 21:44 UTC, Maxusmusti commented
One important note, I've noticed a couple of other things while making these changes:
 - I named the config field `worker`, to be consistent with `gpu`. Should we update these to `workers` and `gpus` for clarity, to show we are specifying an amount? Or is it fine as is?
  - I noticed that `cluster.details()` and our internal `RayCluster` object only show/hold one value for `cpu`, even though we actually have a `min_cpu` and `max_cpu`. Should these be updated to also show/hold both the min and the max properly? (aka the opposite problem of what we had with this PR lol)

2023-08-01 22:58 UTC, tedhtchang commented
It works try the following 
```
cluster = Cluster(ClusterConfiguration(local_interactive=local_interactive, namespace=namespace, name=cluster_name, worker=1, min_cpus=1, max_cpus=1, min_memory=4, max_memory=4, gpu=0, instascale=False, machine_types=["m5.xlarge", "p3.8xlarge"]))
```

![image](https://github.com/project-codeflare/codeflare-sdk/assets/7155778/a9827cd7-2ce3-4524-8577-0c959bff0d05)

2023-08-01 23:13 UTC, jbusche commented
Looks good Mustafa, tried it with:  
```
cluster = Cluster(ClusterConfiguration(
    name='mnisttest',
    namespace='default',
    worker=2,
    min_cpus=2,
    max_cpus=2,
    min_memory=2,
    max_memory=2,
    gpu=0,
    image="quay.io/project-codeflare/ray:2.5.0-py38-cu116",
    instascale=False, # Can be set to false if scaling not needed
    machine_types=["m5.xlarge", "g4dn.xlarge"] # Can be removed if above is false
))
```

2023-08-01 23:13 UTC, tedhtchang reviewed
May need to update these notebooks
demo-notebooks/guided-demos/notebook-ex-outputs/0_basic_ray.ipynb
demo-notebooks/guided-demos/notebook-ex-outputs/3_basic_interactive.ipynb
demo-notebooks/guided-demos/notebook-ex-outputs/2_basic_jobs.ipynb
demo-notebooks/guided-demos/notebook-ex-outputs/4_gpt.ipynb

2023-08-02 17:51 UTC, MichaelClifford requested changes

2023-08-02 17:51 UTC, MichaelClifford commented on src/codeflare_sdk/utils/pretty_print.py
> +        # table1.add_column("Min", style="cyan", no_wrap=True)
should we just delete this line?

2023-08-03 21:54 UTC, tedhtchang reviewed
/lgtm keeping the old notebooks is a great idea.

2023-08-04 00:13 UTC, jbusche commented
/LGTM Thanks Mustafa, I was able to run on my cluster.  Still not quite certain how it all gets folded in so the num_workers and num_gpus begin to work with the codeflare_notebook, but LGTM in testing.

2023-08-04 00:13 UTC, jbusche approved these changes
Tested OK on my OC 4.12 cluster

2023-08-04 15:05 UTC, MichaelClifford approved these changes
Thanks @Maxusmusti changes look good! :rocket:

2023-08-04 15:15 UTC, merged