Github workflow for nightly builds
project-codeflare/codeflare-sdk pull request #307
Opened 2023-08-14 16:13 UTC by jiripetrlik

# Issue link

Closes #291 
# What changes have been made

New workflow was created. It will run each day and produce nightly image for notebook.

# Verification steps
It was tested using my local fork: https://github.com/jiripetrlik/codeflare-sdk/actions/runs/5857794950/job/15880432547

## Checks
- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [*] Manual tests
   - [ ] Testing is not required for this change

2023-08-15 06:56 UTC, sutaakar commented on .github/workflows/nightly-image-build.yaml
> +                cd custom-nb-image
You can use `working-directory` instead - see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun

2023-08-15 06:59 UTC, sutaakar commented on .github/workflows/nightly-image-build.yaml
> +    schedule:
Can you rather use `push` event (i.e. https://github.com/project-codeflare/codeflare-operator/blob/main/.github/workflows/operator-image.yml#L6)?
That way the `dev` image is refreshed immediately.

2023-08-16 09:04 UTC, jiripetrlik commented
@sutaakar Thank you for your comments. I tried to address all of them.

@anishasthana @KPostOffice Hello, can you please take a look and merge if possible?

2023-08-16 10:23 UTC, sutaakar approved these changes

2023-08-16 13:44 UTC, Maxusmusti requested changes
Otherwise LGTM

2023-08-16 13:44 UTC, Maxusmusti commented on .github/workflows/nightly-image-build.yaml
> +            - name: Modify Dockerfile to use locally build SDK
`build` -> `built`

2023-08-16 13:44 UTC, Maxusmusti commented on .github/workflows/nightly-image-build.yaml
> +            - name: Modify Dockerfile to use locally build SDK
For line 36

2023-08-16 13:45 UTC, anishasthana commented on .github/workflows/nightly-image-build.yaml
> +              run: docker build -t quay.io/${{ env.QUAY_ORGANIZATION }}/notebook:${{ env.IMAGE_TAG }} .
nit: I'd prefer to use podman here instead of docker, but I won't block the PR on it.

2023-08-16 13:51 UTC, jiripetrlik commented
@Maxusmusti 
Thank you for the review. Typo should be fixed and PR was rebased.

2023-08-16 13:56 UTC, Maxusmusti approved these changes
LGTM

2023-08-16 14:01 UTC, merged