Refactor unit tests to eliminate pytest warnings
project-codeflare/codeflare-sdk pull request #322
Opened 2023-08-23 11:00 UTC by ChristianZaccaria

# Issue link

Closes #321 

# Cause of Warnings
- 7 of the warnings arise from tests that include a return statement. It seems these should only be making assertions and not returning anything. This way, pytest won't display any warnings.

- The 4 other warnings are related to pkg_resources deprecation. I am unsure where this is coming from (it's not in the repo), it seems like an indirect library call:
![image](https://github.com/project-codeflare/codeflare-sdk/assets/73656840/df4268ea-7296-4b2c-839b-80bf5e9766c6)
Based on this [GitHub issue on google-cloud-python](https://github.com/googleapis/google-cloud-python/issues/11184) and this [PR on ibis repo](https://github.com/ibis-project/ibis/pull/5980), it seems people are inclined to silence these warnings for the meantime.

# Changes
- Refactored to remove return statements from the tests that are run.
- Created the respective support functions.
- Silenced warnings that originate from pkg_resources.

# Verification steps

1. From this branch, run in the terminal `pip install -e .`
2. Then run: `pytest -v tests/unit_test.py`
3. All tests should be passing without any warnings as shown below.

## Checks
- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
![image](https://github.com/project-codeflare/codeflare-sdk/assets/73656840/edb3ac21-8a99-4fd1-897a-3c049be97f32)

2023-08-23 11:13 UTC, Bobbins228 requested changes
Just ran the tests and received no warnings
PR just needs a rebase and it LGTM

2023-08-23 11:37 UTC, ChristianZaccaria commented
> Just ran the tests and received no warnings PR just needs a rebase and it LGTM

Awesome, thanks for testing and reviewing! It's now rebased.

2023-08-23 12:07 UTC, Bobbins228 approved these changes
/LGTM

2023-08-30 18:47 UTC, Maxusmusti approved these changes
LGTM

2023-08-30 18:51 UTC, merged

2023-08-30 20:23 UTC, MichaelClifford commented on tests/unit_test.py
> +from tests.unit_test_support import (
I think you need to add an empty `__init__.py` file to `tests/` so that you can import it this way.