add: abstraction to remove appwrapper visiblilty from NB console.
project-codeflare/codeflare-sdk pull request #380
Opened 2023-10-11 10:49 UTC by VanillaSpoon

# Issue link
closes https://github.com/project-codeflare/codeflare-sdk/issues/365

# What changes have been made
To further abstract the appwrapper from a users perspective, they appwrapper generation has been moved to a hidden folder `.codeflare/appwrapper/<appwrapper.yaml>.`

# Verification steps
`poetry build` 
Install the new .whl for the sdk in a jupyter notebook. 
Open one of the quick-start demos: `git clone https://github.com/project-codeflare/codeflare-sdk`

Follow the process as usual. 

After your clusterconfiguration ensure this is logged:
`Written to: .codeflare/appwrapper/<appwrapper-name.yaml>`

The yaml will no longer appear in the listed files.

From the notebook terminal, you can `cd` to the notebook directory and run `ls -a`. The new hidden directory will be listed `.codeflare`.

run `cd .codflare/appwrapper`  and then `ls`. This will list the generated .yaml. Feel free to inspect it with `vi <appwrapper-name.yaml>` and ensure the appwrapper name and information is correct. 

Continue with  `cluster.up()` and ensure the appwrapper is applied and raycluster is deployed as expected, with the correct cluster info in the kuberay-operator pod logs.

## Checks
- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] Testing is not required for this change

2023-10-12 15:50 UTC, Fiona-Waters commented
Ran through verification steps and can confirm that appwrapper yaml file is written to .codeflare directory. Ran a demo notebook and all works as expected.
/lgtm

2023-10-13 19:54 UTC, Maxusmusti requested changes
One thing to note, I think this should probably be in an absolute path, `~/.codeflare/...` (or expand ~ accordingly to user home dir), rather than a relative path based on current working directory. This way we match the kubernetes pattern of `~/.kube/...`

2023-10-23 09:49 UTC, Bobbins228 reviewed
Tested this and it works as expected
/lgtm

2023-10-30 20:16 UTC, KPostOffice commented
Sorry for the late review, but if we're trying to abstract the creation of the appwrapper from the user, what is the purpose of creating a yaml file at all? Why not just generate the raw text into memory at cluster creation time?

2023-11-02 19:20 UTC, Maxusmusti commented
@KPostOffice Adding the slack comment here as well:

It's something @MichaelClifford, @dimakis, and I have previously discussed, essentially providing the actual yamls themselves is still useful for a lot of users that may want to tweak them with options the SDK doesn't currently support, check them before submitting to their cluster, re-use them, etc.

At the same time, using relative paths was a bit messy, and there were users (mainly BU), who didn't want the AppWrappers generated in their current working dir. So to both organize all codeflare-related assets, as well as to clean/hide implementation details for those who don't care while keeping them accessible for those who do, we ended up deciding on copying the kubernetes ~/.kube/ pattern with ~/.codeflare/ dir for asset management and accessibility

2023-11-07 09:22 UTC, VanillaSpoon commented
Thanks for raising the discussion on this @KPostOffice, and thank you @Maxusmusti for providing additional information :)

2023-11-13 20:06 UTC, KPostOffice approved these changes
/lgtm

2023-11-13 20:11 UTC, merged