Added RayJobSubmission Client wrapper for RCS not created by CodeFlare
project-codeflare/codeflare-sdk pull request #415
Opened 2023-11-29 17:38 UTC by Bobbins228

# Issue link

Closes: #410 
# What changes have been made

Added the `RayJobClient` object for use of RayJobSubmission related commands with the SDK.
This allows us to leverage the SDK to submit jobs to Ray Clusters that were either not created by the SDK or are in a non Kubernetes environment.
# Verification steps

1. Create a Ray Cluster - (I recommend the mnist example RC)
2. Run this example job submission
```
from codeflare_sdk.job.ray_jobs import RayJobClient

client = RayJobClient(
    address="<RAY_DASHBOARD_ADDRESS>"
)

job_id = client.submit_job(
    entrypoint="python mnist.py",
    runtime_env={"working_dir": "./","pip": "requirements.txt"},
)

client.get_job_status(job_id)
```
3. Check the dashboard for the new job which should be running.
4. Try out the other commands listed below
```
client.get_job_info(job_id)
client.get_job_status(job_id)
client.stop_job(job_id)
client.delete_job(job_id)
client.address()

# tail_job_logs returns an Iterator so we must iterate through it and print each line
async for lines in client.tail_job_logs(job_id):
    print(lines, end="") 
```
## Checks
- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] Testing is not required for this change

2023-11-30 12:04 UTC, ChristianZaccaria requested changes
Great job Mark! I left a few requested changes below. Apart from those, I noticed there are some functions that are not unit tested, is there a reason for that? Just thinking about code coverage.

2023-11-30 12:38 UTC, Bobbins228 commented on src/codeflare_sdk/job/ray_jobs.py
> +    def delete_job(self, job_id: str) -> bool:
I don't think we should include the stop function in the delete function as if jobs are completed and the stop command is called it throws false (Stop not needed for successful jobs). 

Also if an exception is called in the stop function the delete functionality will never be reached.

2023-11-30 15:04 UTC, ChristianZaccaria commented
/lgtm

2023-11-30 15:16 UTC, ChristianZaccaria approved these changes
/lgtm thanks!

2023-12-05 16:11 UTC, KPostOffice reviewed
Thanks for the changes. Just some styling and docs nitpicks

2023-12-05 16:11 UTC, KPostOffice commented on src/codeflare_sdk/job/ray_jobs.py
> +    An object for that acts as the Ray Job Submission Client.
This wording seems off.

2023-12-05 16:11 UTC, KPostOffice commented on src/codeflare_sdk/job/ray_jobs.py
> +        """
Can you add a multiline docstring here describing some of the args. This is something I think we should get in the habit of doing to allow for easier navigation and groking by devs

https://peps.python.org/pep-0257/#multi-line-docstrings

2023-12-05 16:11 UTC, KPostOffice commented on src/codeflare_sdk/job/ray_jobs.py
> +        self.rayJobClient = JobSubmissionClient(
https://peps.python.org/pep-0257/#multi-line-docstrings

2023-12-05 16:11 UTC, KPostOffice commented on src/codeflare_sdk/job/ray_jobs.py
> +    def list_jobs(self):
What's the return type here?

2023-12-06 15:14 UTC, Bobbins228 commented
@KPostOffice  Added in the param descriptions from the [ray docs](https://docs.ray.io/en/latest/cluster/running-applications/job-submission/doc/ray.job_submission.JobSubmissionClient.html#ray.job_submission.JobSubmissionClient) and Changed the `list_jobs` return type to `List[JobDetails]`

2023-12-06 17:26 UTC, KPostOffice approved these changes
Thanks for addressing the comments

2023-12-06 17:31 UTC, merged