Added docs for Config and Auth & update doc workflow
project-codeflare/codeflare-sdk pull request #435
Opened 2023-12-21 16:15 UTC by Bobbins228

# Issue link

Closes #429
# What changes have been made

The detailed "code orientated" docs have been moved to a new folder within docs called `detailed-docs`
The release workflow has been updated to account for this.
New docs were added for Cluster Configuration and Authentication

Ingress instructions in README moved to cluster-configuration.md
# Verification steps

You can verify the workflow changes by running this command.
```
poetry run pdoc --html -o docs/detailed-documentation src/codeflare_sdk && pushd docs/detailed-documentation && rm -rf cluster job utils && mv codeflare_sdk/* . && rm -rf codeflare_sdk && popd && find docs/detailed-documentation -type f -name "*.html" -exec bash -c "echo '' >> {}" \;
``` 
You should get a docs/detailed-docs folder containing the detailed documentation.
## Checks
- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] Testing is not required for this change

2024-01-02 12:16 UTC, VanillaSpoon reviewed
Tiny nit, but other than that lgtm, great job @Bobbins228 :)

2024-01-02 12:16 UTC, VanillaSpoon commented on docs/authentication.md
> +    # ca_cert_path="/path/to/cert
Just a small nit, but other than that LGTM, great job @Bobbins228 :)
```diff
- # ca_cert_path="/path/to/cert
+ # ca_cert_path="/path/to/cert"
```

2024-01-03 11:25 UTC, VanillaSpoon reviewed
lgtm :)

2024-01-08 12:51 UTC, ChristianZaccaria requested changes
Looks great! I left a couple nitpicks.

2024-01-08 12:51 UTC, ChristianZaccaria commented on docs/detailed-documentation/cluster/config.html
> +<span>(</span><span>name: str, namespace: str = None, head_info: list = &lt;factory&gt;, head_cpus: int = 2, head_memory: int = 8, head_gpus: int = 0, machine_types: list = &lt;factory&gt;, min_cpus:
This should be reverted to its original path. This must've been generated when running the mentioned poetry command.

2024-01-08 12:51 UTC, ChristianZaccaria commented on docs/detailed-documentation/job/jobs.html
> +<span>(</span><span>script: Optional[str] = None, m: Optional[str] = None, script_args: Optional[List[str]] = None, name: Optional[str] = None, cpu: Optional[int] = None, gpu: Optional[int] = None, m
Here too. This should be reverted to its original path.

2024-01-17 18:15 UTC, Fiona-Waters reviewed
This is great!
Just one comment. I think we should add a `section intro` to the [jobs.html file](https://github.com/project-codeflare/codeflare-sdk/pull/435/files#diff-ce5c4b9fb85fbacb4c8b5c5436b8f13fdc55da7d9b4fdbcac88d0fc2df2d2becR24), so that all sub_modules have one. I think the ... on this page looks like something is missing, especially with the whitespace underneath. 
![image](https://github.com/project-codeflare/codeflare-sdk/assets/76408967/17b7fefa-0b83-441a-ac4b-e342dc99f905)
 What would you think about making these into links so it's clearer where they are coming from? Just a thought.

2024-01-18 12:45 UTC, Bobbins228 commented
@Fiona-Waters 
These html pages are generated off of comments in the code and so the modules jobs, cluster and utils would not generate any notes because they are folders within the SDK. There might be a way to add a description for these modules so that they are generated automatically but I think it would warrant a separate issue WDYT?

2024-01-18 14:41 UTC, Bobbins228 commented
My bad I thought you meant the module yeah I can add a short desc of the DDP Jobs :+1:

2024-01-18 15:28 UTC, Fiona-Waters commented
/lgtm
/approve

2024-01-18 15:30 UTC, merged