Refactor e2e tests to use kueue
project-codeflare/codeflare-sdk pull request #505
Opened 2024-04-10 11:27 UTC by ChughShilpa

# Issue link
<https://issues.redhat.com/browse/RHOAIENG-5239>

# What changes have been made
< Refactored e2e tests to use kueue and not mcad. 
Added steps to create kueue resources such as cluster queue, resource flavour and local queue are created>

# Verification steps
< Execute e2e tests following https://github.com/project-codeflare/codeflare-sdk/blob/main/docs/e2e.md >

## Checks
- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [X ] Manual tests
   - [ ] Testing is not required for this change

2024-04-10 12:53 UTC, sutaakar commented on tests/e2e/kueue_resources_setup.sh
> +      - coveredResources: ["cpu", "memory", "pods", "nvidia.com/gpu"]
IMHO there is no need to cover number of pods.

2024-04-10 13:23 UTC, sutaakar commented
`tests/e2e/mnist_raycluster_sdk_test.py` seems to be a duplication of one test case in `tests/e2e/mnist_raycluster_sdk_oauth_test.py` . IMHO `mnist_raycluster_sdk_test.py` can be removed.

2024-04-11 14:54 UTC, Fiona-Waters requested changes
Just a couple of nitpicks

2024-04-12 13:54 UTC, ChughShilpa commented
> `tests/e2e/mnist_raycluster_sdk_test.py` seems to be a duplication of one test case in `tests/e2e/mnist_raycluster_sdk_oauth_test.py` . IMHO `mnist_raycluster_sdk_test.py` can be removed.

Removed `mnist_raycluster_sdk_test.py` 
Updated dedicated test for kind cluster `assert_jobsubmit_withoutlogin_kind`

2024-04-12 13:57 UTC, ChughShilpa commented on tests/e2e/mnist_raycluster_sdk_oauth_test.py
> +    #    cluster.wait_ready
Added cluster.wait_ready again as the issue has been fixed

2024-04-12 14:14 UTC, Fiona-Waters commented
Ran test against an openshift cluster and it passes as expected.
/lgtm

2024-04-15 06:41 UTC, sutaakar commented on docs/e2e.md
> +  [Disable oauth](https://github.com/project-codeflare/codeflare-operator/blob/main/main.go#L117)
This can be done by modifying `codeflare-operator-config` ConfigMap, disabling `rayDashboardOAuthEnabled` and restarting CFO.

2024-04-15 14:36 UTC, Fiona-Waters commented
I have reviewed again with most recent changes on an openshift cluster - test passed as expected.
/lgtm

2024-04-15 14:42 UTC, sutaakar approved these changes
/lgtm
PR check errors are probably caused by RBAC issues, will be investigated in separate PR

2024-04-15 15:09 UTC, merged