Add notebook annotation to RayCluster
project-codeflare/codeflare-sdk pull request #558
Opened 2024-06-10 10:46 UTC by Ygnas

# Issue link

[https://issues.redhat.com/browse/RHOAIENG-6301](https://issues.redhat.com/browse/RHOAIENG-6301)
# What changes have been made

Added the notebook prefix annotation to RayCluster when it was created from the workbench. That should allow to construct a workbench url for the metrics

# Verification steps

Create a RayCluster from the Data Science Projects Workbench, the created cluster should have an annotation `app.kubernetes.io/managed-by:`

## Checks
- [x] I've made sure the tests are passing. 
- Testing Strategy
   - [x] Unit tests
   - [ ] Manual tests
   - [ ] Testing is not required for this change

2024-06-10 12:28 UTC, Bobbins228 reviewed
/lgtm

2024-06-11 08:13 UTC, Bobbins228 requested changes
Perhaps we could improve the annotation to remove the path to the notebook?
For example my RC was given `app.kubernetes.io/managed-by: /notebook/mark-dsp/mark-wb`

Instead we should aim for `app.kubernetes.io/managed-by: mark-wb`

2024-06-11 08:24 UTC, Fiona-Waters commented
> Perhaps we could improve the annotation to remove the path to the notebook? For example my RC was given `app.kubernetes.io/managed-by: /notebook/mark-dsp/mark-wb`
> 
> Instead we should aim for `app.kubernetes.io/managed-by: mark-wb`

Is there any reason not to use the path here? The reason for the addition of this annotation is to allow the UI team to get the notebook URL for use on the frontend.

2024-06-11 08:29 UTC, Bobbins228 commented
@Fiona-Waters @Ygnas
My bad for not reading the issue correctly. 
/lgtm

2024-06-11 08:40 UTC, Bobbins228 commented
/lgtm

2024-06-11 08:46 UTC, Fiona-Waters approved these changes
Ran through this on my rosa cluster and it works as expected. Looks great to me, thanks Ignas!
/approve

2024-06-11 08:48 UTC, Bobbins228 approved these changes

2024-06-11 09:00 UTC, merged