rm default namespace from demo notebooks
project-codeflare/codeflare-sdk pull request #597
Opened 2024-07-19 22:13 UTC by KPostOffice

# Issue link

# What changes have been made
Remove namespace param from example notebooks

# Verification steps

## Checks
- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [x] Testing is not required for this change

2024-07-20 02:45 UTC, franciscojavierarceo commented
Tests are failing

2024-07-22 11:54 UTC, Bobbins228 commented
/retest

2024-07-22 11:57 UTC, Bobbins228 requested changes

2024-07-22 11:57 UTC, Bobbins228 commented on demo-notebooks/additional-demos/local_interactive.ipynb
> -    "cluster = Cluster(ClusterConfiguration(namespace=namespace,\n",
For this demo and basic interactive the namespace variable is required later for `generate_cert.generate_tls_cert(cluster_name, namespace)`
We could still remove the namespace variable in favour of `generate_cert.generate_tls_cert(cluster_name, cluster.namespace)` WDYT?

2024-07-22 13:24 UTC, Bobbins228 reviewed
/lgtm

2024-07-22 15:52 UTC, Bobbins228 commented
Just a rebase and I am happy to approve

2024-07-22 15:55 UTC, Bobbins228 submitted a review, later dismissed

2024-07-22 15:55 UTC, Bobbins228 commented on demo-notebooks/additional-demos/local_interactive.ipynb
> +    "generate_cert.export_env(cluster_name, cluster.namespace)"
```suggestion
    "generate_cert.export_env(cluster_name, cluster.config.namespace)"
```
My bad. It should be `cluster.config.namespace` for these nbs

2024-07-24 10:22 UTC, Bobbins228 reviewed
/lgtm

2024-07-24 10:25 UTC, merged