Update notebooks and docs with updated Cluster Configuration args
project-codeflare/codeflare-sdk pull request #647
Opened 2024-08-21 14:27 UTC by Ygnas

# Issue link

[https://issues.redhat.com/browse/RHOAIENG-7686](https://issues.redhat.com/browse/RHOAIENG-7686)
# What changes have been made

Update notebooks and docs with updated Cluster Configuration args
# Verification steps

## Checks
- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] Testing is not required for this change

2024-08-21 15:35 UTC, sutaakar commented
@Ygnas Can you please also patch the replacing commands in https://github.com/project-codeflare/codeflare-sdk/blob/main/.github/workflows/guided_notebook_tests.yaml ?

2024-08-21 16:29 UTC, sutaakar commented
/lgtm

2024-08-22 07:56 UTC, Bobbins228 requested changes
Small nit then I'm happy with lgtming this

2024-08-22 07:56 UTC, Bobbins228 commented on docs/cluster-configuration.md
> +    head_extended_resource_requests={'nvidia.com/gpu':0}, # Default 0
```suggestion
    head_extended_resource_requests={'nvidia.com/gpu':0}, # Default {'nvidia.com/gpu': 0}
```
Maybe to be as clear as possible we should specify that the default is a `nvidia.com/gpu`

2024-08-22 07:56 UTC, Bobbins228 commented on docs/cluster-configuration.md
> +    worker_extended_resource_requests={'nvidia.com/gpu':0}, # Default 0
```suggestion
    worker_extended_resource_requests={'nvidia.com/gpu':0}, # Default {'nvidia.com/gpu': 0}
```

2024-08-22 08:22 UTC, Bobbins228 approved these changes
/approve
/lgtm

2024-08-22 08:24 UTC, merged