Enhance common module code documentation
project-codeflare/codeflare-sdk pull request #736
Opened 2024-10-24 08:40 UTC by Ygnas

# Issue link

[https://issues.redhat.com/browse/RHOAIENG-13958](https://issues.redhat.com/browse/RHOAIENG-13958)

# What changes have been made

Enhanced common module code documentation
# Verification steps

## Checks
- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [x] Testing is not required for this change

2024-10-24 09:22 UTC, Bobbins228 requested changes

2024-10-24 09:22 UTC, Bobbins228 commented on src/codeflare_sdk/common/utils/demos.py
> +            The directory to copy the demo notebooks to. Defaults to "./demo-notebooks". overwrite (bool):
```suggestion
            The directory to copy the demo notebooks to. Defaults to "./demo-notebooks". 
```

2024-10-24 09:33 UTC, Bobbins228 reviewed
/lgtm

2024-10-24 10:42 UTC, ChristianZaccaria commented
I'm making a few changes in this repo's settings:
- We are dropping the merge queue feature as it seems it's not properly maintained with major issues found unresolved for over a year.
- One benefit seen from merge queue is that it ensures PRs are tested against the target branch. Since we won't be using this feature, I've enabled "Require branches to be up to date before merging" GitHub feature in this repo. By enabling this, all PRs will require to rebase before they can be merged and this way ensure code stability and integration.

2024-10-25 15:32 UTC, ChristianZaccaria reviewed
Great work! 

Just to confirm, do we want to cover code documentation on only the public functions in the common module?

2024-10-25 15:36 UTC, Ygnas commented
> Great work!
> 
> Just to confirm, do we want to cover code documentation on only the public functions in the common module?

It could cover the private ones as well, but I don't see any private functions appear in the sphinx documentation.

2024-10-25 15:43 UTC, ChristianZaccaria commented
@Ygnas Yeah that's what I thought as well. Perhaps, the private functions can continue to have _simple comments_ while the public functions include the enhanced code documentation for sphynx.

2024-10-25 15:57 UTC, ChristianZaccaria reviewed
/lgtm

2024-10-28 17:09 UTC, KPostOffice reviewed
looks good, a couple of comments

2024-10-28 17:09 UTC, KPostOffice commented on src/codeflare_sdk/common/kubernetes_cluster/auth.py
> +    This function checks if a Kubernetes config file exists at the default path
It also loads from the global variable from auth.py if it's set.

2024-10-28 17:09 UTC, KPostOffice commented on src/codeflare_sdk/common/kueue/kueue.py
> +    as the default queue. If found, the name of the default queue is returned.
add a small comment on the actual label that marks the LQ which marks the queue as the default queue here `kueue.x-k8s.io/default-queue`

2024-11-04 19:01 UTC, KPostOffice approved these changes
/lgtm

2024-11-05 09:23 UTC, Bobbins228 approved these changes
/lgtm /approve

2024-11-05 09:42 UTC, merged