Create ray cluster with ssa
project-codeflare/codeflare-sdk pull request #778
Opened 2024-12-09 16:58 UTC by akram

# Issue link

# What changes have been made
Adding apply function.

# Verification steps

## Checks
- [x] I've made sure the tests are passing. 
- Testing Strategy
   - [x] Unit tests
   - [x] Manual tests
   - [ ] Testing is not required for this change

2024-12-11 10:36 UTC, Bobbins228 requested changes

2024-12-11 10:36 UTC, Bobbins228 commented on src/codeflare_sdk/ray/cluster/cluster.py
> +            raise RuntimeError("Failed to get RayCluster resource: " + str(e))
```suggestion
        self._throw_for_no_raycluster()
```

2024-12-11 10:36 UTC, Bobbins228 commented on src/codeflare_sdk/ray/cluster/cluster.py
> +            raise ValueError(f"Failed to parse resource YAML: {e}")
This `apply()` function only seems to work with written resources.
Have you thought about adding in support for in-memory resources like in [up()](https://github.com/project-codeflare/codeflare-sdk/blob/main/src/codeflare_sdk/ray/cluster/cluster.py#L503-L508)

2024-12-20 12:28 UTC, Bobbins228 reviewed
Can we add user documentation for this PR? 
https://github.com/project-codeflare/codeflare-sdk/blob/main/docs/sphinx/user-docs/ray-cluster-interaction.rst

2025-01-02 15:58 UTC, Bobbins228 requested changes
Began testing this again on both Kind and OpenShift. 
It seems that Appwrapper is not working with the new changes when creating a cluster via `apply()`.

```
TypeError: Discoverer.get() takes 1 positional argument but 2 were given
```

2025-01-02 15:58 UTC, Bobbins228 commented on src/codeflare_sdk/ray/cluster/cluster.py
> +                api_instance = crds.get(api_version, kind="AppWrapper")
```suggestion
                api_instance = crds.get(api_version=api_version, kind="AppWrapper")
```
This should prevent a `TypeError` when trying to create an AppWrapper via `apply()`

2025-01-02 15:59 UTC, Bobbins228 commented on src/codeflare_sdk/ray/cluster/cluster.py
> +                api_instance = crds.get(api_version, kind="AppWrapper")
Even with the update to the api_instance there are still errors when trying to apply AppWrappers.
```
Response: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"PatchOptions.meta.k8s.io \\"\\" is invalid: fieldManager: Required value: is required for apply patch","reason":"Invalid","details":{"group":"meta.k8s.io","kind":"PatchOptions","causes":[{"reason":"FieldValueRequired","message":"Required value: is required for apply patch","field":"fieldManager"}]},"code":422}\n'
```

2025-01-02 21:52 UTC, KPostOffice commented on src/codeflare_sdk/ray/cluster/cluster.py
> +        field_manager="cluster-manager",
This should probably be `cf-sdk` or something similar and pulled out into a variable, used both here and for the AppWrapper

2025-01-02 21:52 UTC, KPostOffice commented on src/codeflare_sdk/ray/cluster/cluster.py
> +        """Return a dynamic client, optionally mocked in tests."""
Is this doc string intended here?

2025-01-02 21:52 UTC, KPostOffice commented on src/codeflare_sdk/ray/cluster/cluster.py
> +def _apply_resources(
Could you just use a [partial](https://www.geeksforgeeks.org/partial-functions-python/) instead of pulling this into it's own function?

2025-01-07 11:52 UTC, akram commented on src/codeflare_sdk/ray/cluster/cluster.py
> +                api_instance = crds.get(api_version, kind="AppWrapper")
I added the field-manager field to the server_side_apply call (for AppWrapper). That should have fixed it.
I cannot reproduce it now, and I see the AppWrapper being properly created.

2025-01-07 11:53 UTC, akram commented
> Began testing this again on both Kind and OpenShift. It seems that Appwrapper is not working with the new changes when creating a cluster via `apply()`.
> 
> ```
> TypeError: Discoverer.get() takes 1 positional argument but 2 were given
> ```

I have encapsulated the exception and was not able to reproduce the exact issue here. 
Instead I was seeing an issue related to `appwrapper` not being enabled.

2025-01-07 12:48 UTC, Bobbins228 reviewed
Tested this again and Appwrapper is working for initial apply but I ran into a couple of issues when trying to update the AppWrapper and apply my changes. 

I kept running into this error with regards to the field manager even with `force=True`:
```
A conflict occurred with the RayCluster resource.
Only one RayCluster with the same name is allowed. Please delete or rename the existing RayCluster before creating a new one with the desired name.
Response: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Apply failed with 1 conflict: conflict with \\"codeflare-operator\\" using workload.codeflare.dev/v1beta2: .spec.components","reason":"Conflict","details":{"causes":[{"reason":"FieldManagerConflict","message":"conflict with \\"codeflare-operator\\" using workload.codeflare.dev/v1beta2","field":".spec.components"}]},"code":409}\n'
```

2025-01-07 17:43 UTC, akram commented
> Tested this again and Appwrapper is working for initial apply but I ran into a couple of issues when trying to update the AppWrapper and apply my changes.
> 
> I kept running into this error with regards to the field manager even with `force=True`:
> 
> ```
> A conflict occurred with the RayCluster resource.
> Only one RayCluster with the same name is allowed. Please delete or rename the existing RayCluster before creating a new one with the desired name.
> Response: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Apply failed with 1 conflict: conflict with \\"codeflare-operator\\" using workload.codeflare.dev/v1beta2: .spec.components","reason":"Conflict","details":{"causes":[{"reason":"FieldManagerConflict","message":"conflict with \\"codeflare-operator\\" using workload.codeflare.dev/v1beta2","field":".spec.components"}]},"code":409}\n'
> ```


nice catch. I reproduced it. There is 2 issues actually. For appwrappers, I was not propagating the force=True .
But, on top of that, changing the `spec.components[0].template` is also blocked by webhooks.
I tried to update the mutating webhook the same way I did for raycluster oauth proxy field, but that's not working.
The validating webhook is currently enforcing the `raycluster.template` to be immutable.

Trying to edit an appwrapper manually with `oc edit` leads to the same error.
```
(codeflare-sdk-py3.9) akram@wadez-m1 codeflare-sdk % oc edit appwrappers.workload.codeflare.dev jobtest
error: appwrappers.workload.codeflare.dev "jobtest" could not be patched: admission webhook "vappwrapper.kb.io" denied the request: spec.components[0].template.raw: Forbidden: attempt to change immutable field
```

2025-01-07 17:48 UTC, dgrove-oss commented
AppWrappers enforce that spec.components[*].template is immutable after creation, because updates may invalidate the PodSet info that they've extracted and given to Kueue.   

I'm missing the bigger context of what you are trying to do, but you will not be able to mutate a RayCluster wrapped in an AppWrapper in place.

2025-01-08 09:42 UTC, akram commented
> AppWrappers enforce that spec.components[*].template is immutable after creation, because updates may invalidate the PodSet info that they've extracted and given to Kueue.
> 
> I'm missing the bigger context of what you are trying to do, but you will not be able to mutate a RayCluster wrapped in an AppWrapper in place.

hi @dgrove-oss ,
the goal of this PR is to introduce an `apply()` function that would avoid cases where users have to do down+up to update rayclusers and appwrappers. That's an idempotent alternative to the `up()` function that can also makes resource creation more straitghtforward.

2025-01-16 01:10 UTC, KPostOffice commented on src/codeflare_sdk/ray/cluster/cluster.py
> +def _apply_resources(
Can you rename this to make it clear that it is specific to ray clusters

2025-01-16 01:11 UTC, KPostOffice reviewed
Overall lgtm, just one nit

2025-01-17 13:55 UTC, akram commented on src/codeflare_sdk/ray/cluster/cluster.py
> +def _apply_resources(
done

2025-01-17 14:15 UTC, akram commented
@KPostOffice and @Bobbins228 do you think we can merge it?
right now, error states are already handled in `_kube_api_error_handling` and explicit error messages are provided.

2025-01-27 16:06 UTC, Bobbins228 approved these changes
/lgtm

2025-01-28 11:04 UTC, Bobbins228 commented
/approve

2025-01-28 17:14 UTC, merged