Add annotations parameter
project-codeflare/codeflare-sdk pull request #785
Opened 2024-12-19 12:13 UTC by Bobbins228

# Issue link

[RHOAIENG-16029](https://issues.redhat.com/browse/RHOAIENG-16029)
# What changes have been made

* Added `annotations` parameter for ClusterConfiguration
* Added Unit Test for new parameter
* Updated user docs
# Verification steps

## Setup
### Notebook server ODH/RHOAI/Local
* Clone this repository with `git clone https://github.com/project-codeflare/codeflare-sdk.git`
* Checkout this PR's branch
* Run `poetry build` - install if needed (`pip install poetry`)
* Run `pip install --force-reinstall dist/codeflare_sdk-0.0.0.dev0-py3-none-any.whl` 
* Restart your notebook kernel
## Testing
* Create a Ray Cluster using the `annotations` parameter `annotations = {"key":"value"}`
* Ensure the annotations exist on the Cluster
## Additional testing
Run the same testing steps above in a RHOAI notebook.
Ensure that the notebook managedby annotation is appended to the user defined annotations
## Checks
- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] Testing is not required for this change

2024-12-20 10:01 UTC, Ygnas approved these changes

2024-12-20 20:49 UTC, KPostOffice requested changes
Looks, good. One comment though

2025-01-02 10:12 UTC, Ygnas approved these changes

2025-01-02 12:42 UTC, Ygnas approved these changes

2025-01-02 13:29 UTC, ChristianZaccaria commented on src/codeflare_sdk/ray/cluster/build_ray_cluster.py
> +def with_nb_annotations(annotations):
nit: explicitly add the type:
```suggestion
def with_nb_annotations(annotations: dict):
```

2025-01-02 15:31 UTC, ChristianZaccaria approved these changes
/lgtm

2025-01-02 21:24 UTC, KPostOffice approved these changes

2025-01-02 21:25 UTC, merged